/*
CREATE DATABASE [InDocEdge$scheduler_dbss_1217_20251114_dbss] ON (NAME = InDocEdge$scheduler_Data, FILENAME = 'X:\MCDB07_SQLDATA\InDocEdge$scheduler_Data_ss') AS SNAPSHOT OF [InDocEdge$scheduler];
*/
/*
CREATE TABLE UPDATED_TRIGGERS 
([UPDATED_TRIGGER_NAME] [nvarchar](150), 
UPDATED bit default 0, 
UPDATED_TIME datetime2 default null)

INSERT INTO UPDATED_TRIGGERS (UPDATED_TRIGGER_NAME)
SELECT [TRIGGER_NAME]
FROM [InDocEdge$scheduler].[dbo].[QRTZ_TRIGGERS] sch
	WHERE NEXT_FIRE_TIME = 638987256072000000
*/

CREATE TABLE #TOUPDATE ([UPDATED_TRIGGER_NAME_TEMP] [nvarchar](150));

	INSERT INTO #TOUPDATE ([UPDATED_TRIGGER_NAME_TEMP])
	SELECT TOP 100 [UPDATED_TRIGGER_NAME] 
	FROM [UPDATED_TRIGGERS]
	WHERE UPDATED = 0

BEGIN TRAN

	UPDATE s
	SET s.NEXT_FIRE_TIME = r.NEXT_FIRE_TIME 
	FROM [InDocEdge$scheduler].[dbo].[QRTZ_TRIGGERS] s
		INNER JOIN [_Renato_].[dbo].[QRTZ_TRIGGERS] r 
			ON s.TRIGGER_NAME = r.TRIGGER_NAME 
	WHERE s.TRIGGER_NAME IN (
			SELECT tu.[UPDATED_TRIGGER_NAME_TEMP] 
				FROM #TOUPDATE tu
				INNER JOIN [InDocEdge$scheduler].[dbo].[QRTZ_TRIGGERS]  ss
					ON tu.[UPDATED_TRIGGER_NAME_TEMP] = ss.TRIGGER_NAME
				WHERE ss.NEXT_FIRE_TIME = 638987256072000000)


	UPDATE UPDATED_TRIGGERS
	SET UPDATED = 1, UPDATED_TIME = SYSDATETIME()
	WHERE [UPDATED_TRIGGER_NAME] IN 
		(SELECT [UPDATED_TRIGGER_NAME_TEMP] FROM #TOUPDATE)

	DROP TABLE #TOUPDATE

	/*
ROLLBACK
	*/
	/*
COMMIT
	*/